/**
 * Short anonymous-share redirect.
 *
 * `cesafiu.ro/quiz` → `cesafiu.ro/<default-locale>/test/scenarii?utm_*`
 *
 * Used as the footer URL on cards generated by users who are not signed in
 * (and therefore have no referral code). Drops the visitor directly into the
 * first quiz, with UTM tags so the anonymous share traffic is attributable
 * in Umami even without per-user attribution.
 *
 * See docs/VIRAL-PHASE-D-PLAN.md §5 D1.1.
 */

import {NextResponse} from 'next/server';
import type {NextRequest} from 'next/server';
import {defaultLocale} from '@/i18n/config';
import {publicOriginFromRequest} from '@/lib/server/request-origin';

export async function GET(request: NextRequest) {
  // Build against the public origin (not request.url) so Railway's internal
  // http://localhost:8080 doesn't end up in the Location header.
  const target = new URL(`/${defaultLocale}/test/scenarii`, publicOriginFromRequest(request));
  target.searchParams.set('utm_source', 'share');
  target.searchParams.set('utm_medium', 'card');
  target.searchParams.set('utm_campaign', 'anonymous_share');
  return NextResponse.redirect(target, {status: 302});
}
