// CeSaFiu — quiz data, deep tests, careers, universities, paths
window.QUIZ_DATA = {
  // ── QUICK QUIZ (vibe / 6 întrebări) ──
  questions: [
    {
      id: 'q1', sticker: '01 / 06', stickerColor: 'yellow',
      title: 'Sâmbătă seara. Cum arată vibe-ul tău?',
      subtitle: 'Nu există răspuns greșit. Doar tu, autentic.',
      options: [
        { id: 'a', label: 'Construiesc ceva — un site, un proiect, ceva tangibil', tag: 'BUILDER', traits: ['build', 'tech'] },
        { id: 'b', label: 'Ies cu prietenii și organizez tot grupul', tag: 'CONNECTOR', traits: ['social', 'lead'] },
        { id: 'c', label: 'Citesc, scriu, sau mă pierd într-un documentar', tag: 'THINKER', traits: ['analyze', 'create'] },
        { id: 'd', label: 'Editez clipuri / desenez / fac muzică', tag: 'CREATOR', traits: ['create', 'visual'] },
      ],
    },
    {
      id: 'q2', sticker: '02 / 06', stickerColor: 'green',
      title: 'Care problemă te enervează cel mai tare?',
      subtitle: 'Cea pe care simți că TU ai putea-o rezolva.',
      options: [
        { id: 'a', label: 'Apps proaste care nu fac sens. Pierdere de timp.', tag: 'UX', traits: ['build', 'analyze'] },
        { id: 'b', label: 'Oameni care nu se înțeleg între ei.', tag: 'EMPATHY', traits: ['social', 'analyze'] },
        { id: 'c', label: 'Informații false care circulă peste tot.', tag: 'TRUTH', traits: ['analyze', 'lead'] },
        { id: 'd', label: 'Lucruri urâte care ar putea arăta mult mai bine.', tag: 'AESTHETIC', traits: ['create', 'visual'] },
      ],
    },
    {
      id: 'q3', sticker: '03 / 06', stickerColor: 'purple',
      title: 'Profesorul îți dă proiect liber. Tu alegi:',
      subtitle: 'Ce te face să vrei să stai treaz până la 3 dimineața?',
      options: [
        { id: 'a', label: 'Să programez un joc / o aplicație care chiar funcționează', tag: 'CODE', traits: ['build', 'tech'] },
        { id: 'b', label: 'Să fac un documentar / podcast despre ceva real', tag: 'STORY', traits: ['create', 'analyze'] },
        { id: 'c', label: 'Să organizez un eveniment care adună oameni', tag: 'EVENT', traits: ['social', 'lead'] },
        { id: 'd', label: 'Să cercetez o întrebare ciudată până găsesc răspunsul', tag: 'RESEARCH', traits: ['analyze', 'tech'] },
      ],
    },
    {
      id: 'q4', sticker: '04 / 06', stickerColor: 'yellow',
      title: 'În 10 ani te vezi:',
      subtitle: 'Fii sincer. Nu cu ce zice mama.',
      options: [
        { id: 'a', label: 'Cu propria afacere / produs lansat', tag: 'FOUNDER', traits: ['build', 'lead'] },
        { id: 'b', label: 'Schimbând cum funcționează un sistem mare', tag: 'IMPACT', traits: ['lead', 'analyze'] },
        { id: 'c', label: 'Făcând artă / conținut care contează', tag: 'ARTIST', traits: ['create', 'visual'] },
        { id: 'd', label: 'Lucrând cu oameni — ajutând, mentorând, conectând', tag: 'HELPER', traits: ['social', 'analyze'] },
      ],
    },
    {
      id: 'q5', sticker: '05 / 06', stickerColor: 'green',
      title: 'Ce te încarcă cu energie?',
      subtitle: 'Ce faci când ai 2 ore libere și nimeni nu te vede?',
      options: [
        { id: 'a', label: 'Să rezolv un puzzle / să debugez un cod', tag: 'PROBLEM', traits: ['analyze', 'tech'] },
        { id: 'b', label: 'Să discut cu cineva despre viața lor', tag: 'TALK', traits: ['social', 'analyze'] },
        { id: 'c', label: 'Să creez ceva vizual — moodboard, video, design', tag: 'MAKE', traits: ['create', 'visual'] },
        { id: 'd', label: 'Să citesc despre ceva complet nou pentru mine', tag: 'LEARN', traits: ['analyze', 'create'] },
      ],
    },
    {
      id: 'q6', sticker: '06 / 06', stickerColor: 'purple',
      title: 'Ultima întrebare. Banii sau impactul?',
      subtitle: 'Răspunde rapid. Prima reacție.',
      options: [
        { id: 'a', label: 'Banii. Vreau libertate și opțiuni.', tag: 'AMBITION', traits: ['build', 'lead'] },
        { id: 'b', label: 'Impactul. Vreau să las ceva în urmă.', tag: 'PURPOSE', traits: ['lead', 'social'] },
        { id: 'c', label: 'Echilibru. Pot avea amândouă.', tag: 'BALANCE', traits: ['analyze', 'social'] },
        { id: 'd', label: 'Procesul. Banii și impactul vin pe parcurs.', tag: 'CRAFT', traits: ['create', 'build'] },
      ],
    },
  ],

  // ── PERSONALITY (Big Five-inspired, 1–5 Likert) ──
  // dim: O=Openness, C=Conscientiousness, E=Extraversion, A=Agreeableness, N=Neuroticism. r = reverse-scored.
  personality: {
    name: 'Test de personalitate',
    subtitle: 'Big Five — adaptat ca să nu te plictisești',
    estimateMin: 4,
    items: [
      { id: 'p01', dim: 'O', text: 'Mă pierd în idei noi mai des decât majoritatea oamenilor.' },
      { id: 'p02', dim: 'O', text: 'Îmi plac discuțiile abstracte — filosofie, „ce-ar fi dacă", teorii.' },
      { id: 'p03', dim: 'O', r: true, text: 'Prefer rutina familiară decât să încerc lucruri ciudate.' },
      { id: 'p04', dim: 'C', text: 'Când îmi propun ceva, duc la capăt chiar dacă devine plictisitor.' },
      { id: 'p05', dim: 'C', r: true, text: 'Las lucrurile pentru ultima clipă mai des decât aș vrea să recunosc.' },
      { id: 'p06', dim: 'C', text: 'Îmi place când ziua mea are structură.' },
      { id: 'p07', dim: 'E', text: 'Mă încarc cu energie când sunt înconjurat de oameni.' },
      { id: 'p08', dim: 'E', r: true, text: 'După un eveniment social mare am nevoie să stau singur câteva ore.' },
      { id: 'p09', dim: 'E', text: 'Vorbesc primul în grup, fără să mă gândesc prea mult.' },
      { id: 'p10', dim: 'A', text: 'Observ rapid când cineva e supărat, chiar dacă nu o spune.' },
      { id: 'p11', dim: 'A', r: true, text: 'Pun ce vreau eu pe primul loc, fără remușcări.' },
      { id: 'p12', dim: 'A', text: 'Îmi place să ajut, chiar și când nu mi se cere.' },
      { id: 'p13', dim: 'N', text: 'Mă stresez ușor când lucrurile nu merg conform planului.' },
      { id: 'p14', dim: 'N', r: true, text: 'Mă recuperez rapid emoțional după un eșec.' },
      { id: 'p15', dim: 'N', text: 'Gândurile negre revin uneori și nu prea le pot opri.' },
    ],
    dimensions: {
      O: { name: 'Deschidere', short: 'OPEN', color: 'purple', high: 'Curiozitate, creativitate, ideile abstracte te încarcă.', low: 'Practică, focus pe ce funcționează deja.' },
      C: { name: 'Conștiinciozitate', short: 'PLAN', color: 'green', high: 'Disciplină, structură, duci la capăt.', low: 'Spontan, flexibil, mai puțin rigid pe planuri.' },
      E: { name: 'Extraversiune', short: 'PEOPLE', color: 'yellow', high: 'Te încarci cu oameni, vorbești ușor, iei inițiativa.', low: 'Energie internă, preferi grupuri mici sau singur.' },
      A: { name: 'Agreabilitate', short: 'CARE', color: 'green', high: 'Empatic, cooperant, atent la ceilalți.', low: 'Direct, competitiv, pui propriile interese pe primul loc.' },
      N: { name: 'Stabilitate emoțională', short: 'CALM', color: 'purple', high: 'Sensibil emoțional — simți totul intens.', low: 'Calm sub presiune, te recuperezi rapid.' },
    },
  },

  // ── VOCATIONAL (RIASEC / Holland Code, forced-choice 12 perechi) ──
  // Each item has two options, each contributes 1 point to one of: R, I, A, S, E, C
  vocational: {
    name: 'Test vocațional',
    subtitle: 'Holland Code (RIASEC) — îți spune CE TE atrage la o activitate',
    estimateMin: 5,
    items: [
      { id: 'v01', a: { text: 'Repari o bicicletă stricată', code: 'R' }, b: { text: 'Studiezi de ce un motor face zgomot', code: 'I' } },
      { id: 'v02', a: { text: 'Pictezi un perete dintr-un café', code: 'A' }, b: { text: 'Ții un workshop pentru elevi mai mici', code: 'S' } },
      { id: 'v03', a: { text: 'Conduci o echipă într-un proiect', code: 'E' }, b: { text: 'Organizezi un buget Excel impecabil', code: 'C' } },
      { id: 'v04', a: { text: 'Construiești un raft din lemn', code: 'R' }, b: { text: 'Compui o melodie originală', code: 'A' } },
      { id: 'v05', a: { text: 'Scrii un eseu cercetător', code: 'I' }, b: { text: 'Vinzi un produs la o expoziție', code: 'E' } },
      { id: 'v06', a: { text: 'Ajuți o colegă cu temele', code: 'S' }, b: { text: 'Sortezi documente după reguli stricte', code: 'C' } },
      { id: 'v07', a: { text: 'Faci un experiment de chimie', code: 'I' }, b: { text: 'Planifici un eveniment de 100 oameni', code: 'E' } },
      { id: 'v08', a: { text: 'Filmezi un scurt documentar', code: 'A' }, b: { text: 'Faci voluntariat la o cantină', code: 'S' } },
      { id: 'v09', a: { text: 'Programezi un site web', code: 'I' }, b: { text: 'Faci un raport contabil', code: 'C' } },
      { id: 'v10', a: { text: 'Organizezi rafturi într-un magazin', code: 'C' }, b: { text: 'Antrenezi o echipă sportivă', code: 'R' } },
      { id: 'v11', a: { text: 'Negociezi un contract', code: 'E' }, b: { text: 'Scrii o piesă de teatru', code: 'A' } },
      { id: 'v12', a: { text: 'Mentorezi un coleg nou', code: 'S' }, b: { text: 'Repari o instalație electrică', code: 'R' } },
    ],
    codes: {
      R: { name: 'Realist', short: 'DOERS', color: 'green', desc: 'Mâini active. Tools, mașini, sport, construit. Înveți făcând.' },
      I: { name: 'Investigativ', short: 'THINKERS', color: 'purple', desc: 'Curiozitate, cercetare, date, întrebări „de ce". Lab brain.' },
      A: { name: 'Artistic', short: 'CREATORS', color: 'yellow', desc: 'Exprimare, estetică, originalitate. Vizual, muzică, scris, video.' },
      S: { name: 'Social', short: 'HELPERS', color: 'green', desc: 'Oameni, empatie, predare, îngrijire. Energie din relații.' },
      E: { name: 'Întreprinzător', short: 'LEADERS', color: 'purple', desc: 'Influență, persuasiune, vânzări, conducere, business.' },
      C: { name: 'Convențional', short: 'ORGANIZERS', color: 'yellow', desc: 'Sisteme, proceduri, date organizate, acuratețe, fiabilitate.' },
    },
  },

  // ── CAREERS — extins cu freelance/antreprenor/auto-didact ──
  careers: [
    {
      id: 'product-designer', name: 'Product Designer',
      tagline: 'Faci ca apps proaste să devină geniale',
      color: 'purple', emoji: '✦',
      pathType: 'mixt', // facultate | bootcamp | autodidact | antreprenor | mixt
      traits: ['build', 'create', 'analyze', 'visual'],
      riasec: ['A', 'I', 'E'], big5: ['O', 'C'],
      salary: '4.500 — 12.000 €/lună', demand: 'Foarte mare', vibe: 'Creativ + tehnic',
      description: 'Design-erul de produs decide cum se simte și cum funcționează un app. Mix de psihologie, estetică și logică.',
      day: ['Discuții cu utilizatori despre cum folosesc app-ul', 'Schițe rapide pentru un flow nou', 'Prototip clickabil în Figma', 'Critique cu echipa de inginerie', 'Iterații pe baza feedback-ului'],
      skills: ['Figma', 'User research', 'Prototyping', 'Sistem design', 'Strategie'],
      paths: ['UX Designer', 'Product Manager', 'Design Lead', 'Founder'],
      schools: ['UNARTE București', 'UAUIM', 'UBB Cluj — Design'],
    },
    {
      id: 'data-scientist', name: 'Data Scientist',
      tagline: 'Citești poveștile pe care le ascund cifrele',
      color: 'green', emoji: '◆',
      pathType: 'facultate',
      traits: ['analyze', 'tech', 'build'],
      riasec: ['I', 'C', 'R'], big5: ['O', 'C'],
      salary: '5.000 — 14.000 €/lună', demand: 'Extremă', vibe: 'Analitic + curios',
      description: 'Iei date haotice și descoperi pattern-uri pe care nimeni nu le-a văzut. Pe scurt: detectiv, dar pentru cifre.',
      day: ['Curățare date dintr-un dataset uriaș', 'Test A/B pe o feature nouă', 'Build model ML', 'Prezentare insight-uri la echipă', 'Documentare metodă'],
      skills: ['Python', 'SQL', 'Statistică', 'Machine Learning', 'Storytelling'],
      paths: ['ML Engineer', 'Data Lead', 'Researcher', 'Strategy Consultant'],
      schools: ['Politehnica București', 'ASE', 'UBB Cluj — Math/CS'],
    },
    {
      id: 'creative-director', name: 'Creative Director',
      tagline: 'Spui povești care fac oameni să se oprească',
      color: 'yellow', emoji: '✺',
      pathType: 'mixt',
      traits: ['create', 'visual', 'lead', 'social'],
      riasec: ['A', 'E', 'S'], big5: ['O', 'E'],
      salary: '6.000 — 20.000 €/lună', demand: 'Mare', vibe: 'Vizionar + curajos',
      description: 'Conduci direcția vizuală și de poveste. Decizi cum arată și cum sună un brand sau un produs.',
      day: ['Brainstorm campanie nouă', 'Review cu echipa de design', 'Pitch la client', 'Feedback pe video edits', 'Mood-board pentru următorul sezon'],
      skills: ['Storytelling', 'Brand strategy', 'Direcție artistică', 'Lider de echipă', 'Pitching'],
      paths: ['Brand Lead', 'Founder de studio', 'Production Director', 'CMO'],
      schools: ['UNATC', 'UNARTE', 'SNSPA — Comunicare'],
    },
    {
      id: 'social-entrepreneur', name: 'Antreprenor Social',
      tagline: 'Construiești ceva ce schimbă comunități',
      color: 'purple', emoji: '✿',
      pathType: 'antreprenor',
      traits: ['lead', 'social', 'build', 'analyze'],
      riasec: ['E', 'S', 'I'], big5: ['E', 'A'],
      salary: 'Variabil — depinde de impact', demand: 'În creștere', vibe: 'Misionar + practic',
      description: 'Identifici o problemă socială și construiești o soluție sustenabilă în jurul ei. Business cu suflet.',
      day: ['Discuții cu beneficiari', 'Pitch la investitori cu impact', 'Strategie operațională', 'Recrutare voluntari', 'Măsurare impact'],
      skills: ['Strategie', 'Fundraising', 'Empatie radicală', 'Operațiuni', 'Comunicare'],
      paths: ['Founder ONG', 'Impact investor', 'Policy advisor', 'Educator'],
      schools: ['SNSPA', 'ASE — Antreprenoriat', 'UBB — Sociologie'],
    },
    {
      id: 'researcher', name: 'Cercetător',
      tagline: 'Pui întrebări pe care nimeni nu le-a pus',
      color: 'green', emoji: '◉',
      pathType: 'facultate',
      traits: ['analyze', 'create', 'tech'],
      riasec: ['I', 'A'], big5: ['O', 'C'],
      salary: '3.500 — 9.000 €/lună', demand: 'Stabilă', vibe: 'Profund + obsesiv',
      description: 'Te bagi adânc într-un subiect și ieși cu răspunsuri pe care nimeni nu le avea. Academic sau industrie.',
      day: ['Citit ultimele lucrări științifice', 'Setup experiment', 'Analiză rezultate', 'Scris articol', 'Discuții cu colaboratori'],
      skills: ['Gândire critică', 'Metodologie', 'Scris academic', 'Limbi străine', 'Răbdare'],
      paths: ['PhD', 'Researcher industrie', 'Profesor', 'Consultant'],
      schools: ['UB', 'UBB', 'Politehnica'],
    },
    {
      id: 'community-builder', name: 'Community Builder',
      tagline: 'Faci ca oamenii să se simtă acasă undeva',
      color: 'yellow', emoji: '❉',
      pathType: 'mixt',
      traits: ['social', 'create', 'lead'],
      riasec: ['S', 'E', 'A'], big5: ['E', 'A'],
      salary: '2.500 — 7.000 €/lună', demand: 'În creștere', vibe: 'Cald + strategic',
      description: 'Construiești și hrănești comunități online sau offline. Cunoști oameni, organizezi, faci legături.',
      day: ['Răspuns la mesaje în comunitate', 'Planificare eveniment', 'Onboarding membri noi', 'Content pentru newsletter', 'Conversații 1-1'],
      skills: ['Empatie', 'Organizare', 'Comunicare', 'Strategie de conținut', 'Facilitare'],
      paths: ['Head of Community', 'Event Lead', 'Brand Manager', 'Founder'],
      schools: ['SNSPA', 'UB — Comunicare', 'UNATC'],
    },
    // ── NEW: freelance / autodidact / antreprenor ──
    {
      id: 'freelance-developer', name: 'Freelance Developer',
      tagline: 'Cod plătit per proiect, fără șef',
      color: 'green', emoji: '⌘',
      pathType: 'autodidact',
      traits: ['build', 'tech', 'analyze'],
      riasec: ['I', 'R', 'E'], big5: ['C', 'O'],
      salary: '40 — 120 €/oră', demand: 'Foarte mare', vibe: 'Independent + tehnic',
      description: 'Construiești site-uri, apps și automatizări pentru clienți, de oriunde. Înveți singur, livrezi rapid, factura ta.',
      day: ['Standup cu un client de pe Slack', 'Sesiune de cod pe un feature', 'Email cu propuneri pentru un proiect nou', 'Code review pentru un colaborator', 'Studiu seara pe un framework nou'],
      skills: ['JavaScript / TypeScript', 'Git', 'Cloud (Vercel/AWS)', 'Negociere prețuri', 'Self-discipline'],
      paths: ['Senior Freelancer', 'Studio owner', 'SaaS founder', 'Tech consultant'],
      schools: ['Autodidact (FreeCodeCamp, The Odin Project)', 'Bootcamp (Codecool, Wantsome)', 'PUB / UBB (opțional)'],
    },
    {
      id: 'content-creator', name: 'Content Creator',
      tagline: 'Audiența ta = cariera ta',
      color: 'yellow', emoji: '★',
      pathType: 'autodidact',
      traits: ['create', 'visual', 'social'],
      riasec: ['A', 'E', 'S'], big5: ['E', 'O'],
      salary: '500 — 30.000 €/lună (volatil)', demand: 'Saturată dar nișată', vibe: 'Public + obsesiv',
      description: 'TikTok, YouTube, podcast, newsletter. Construiești o audiență în jurul unei voci sau pasiuni și monetizezi prin sponsorizări, produse, abonamente.',
      day: ['Idei de conținut din comentarii', 'Filmare / înregistrare', 'Editare brutal de fast', 'Răspunsuri la comunitate', 'Briefing cu un brand'],
      skills: ['Storytelling', 'Editare video', 'Algoritm awareness', 'Brand deals', 'Consistență'],
      paths: ['Creator full-time', 'Studio de producție', 'Founder produs', 'Consultant brand'],
      schools: ['Autodidact (YouTube + reps)', 'UNATC (opțional)', 'Cursuri online — Skillshare/Domestika'],
    },
    {
      id: 'startup-founder', name: 'Startup Founder',
      tagline: 'Construiești de la zero ceva ce nu există',
      color: 'purple', emoji: '⚡',
      pathType: 'antreprenor',
      traits: ['build', 'lead', 'analyze', 'social'],
      riasec: ['E', 'I', 'A'], big5: ['O', 'C', 'E'],
      salary: '0 până la milioane (binar)', demand: 'Mereu', vibe: 'Risc + viziune',
      description: 'Identifici o problemă, validezi cu utilizatori, ridici fonduri sau bootstrap, scalezi. Cariera cea mai grea și cea mai liberă.',
      day: ['Customer interviews dimineața', 'Sprint planning cu echipa', 'Pitch la investitor', 'Hiring pentru rol cheie', 'Strategie financiară noaptea'],
      skills: ['Sales', 'Product sense', 'Hiring', 'Reziliență', 'Storytelling pentru pitch'],
      paths: ['Serial founder', 'Investor / VC', 'Operator la altă companie', 'Mentor'],
      schools: ['ASE — Antreprenoriat', 'YCombinator Startup School (online)', 'Innovation Labs RO', 'Techstars'],
    },
    {
      id: 'freelance-designer', name: 'Freelance Designer',
      tagline: 'Brandurile vin la tine, nu invers',
      color: 'yellow', emoji: '✎',
      pathType: 'autodidact',
      traits: ['create', 'visual', 'build'],
      riasec: ['A', 'E'], big5: ['O', 'C'],
      salary: '30 — 90 €/oră', demand: 'Mare', vibe: 'Estetic + business',
      description: 'Logo-uri, identități vizuale, site-uri pentru clienți direct. Portofoliul tău e CV-ul. Mâinile tale sunt firma.',
      day: ['Discovery call cu un client nou', 'Concepte rapide pe hârtie', 'Schițe în Figma', 'Prezentare pe Zoom', 'Facturare + admin'],
      skills: ['Figma / Illustrator', 'Tipografie', 'Branding', 'Pricing', 'Comunicare client'],
      paths: ['Studio mic', 'Art director', 'In-house lead', 'Educator'],
      schools: ['Autodidact (Behance reps)', 'UNARTE', 'Domestika / School of Motion'],
    },
    {
      id: 'crafts-entrepreneur', name: 'Antreprenor Craft',
      tagline: 'Faci cu mâna, vinzi online',
      color: 'green', emoji: '✤',
      pathType: 'antreprenor',
      traits: ['create', 'build', 'visual'],
      riasec: ['R', 'A', 'E'], big5: ['C', 'O'],
      salary: '1.500 — 8.000 €/lună', demand: 'Nișată', vibe: 'Tactil + autentic',
      description: 'Ceramică, lemn, textile, parfumerie naturală — produse pe care le faci tu și le vinzi pe Instagram, târguri, propriul shop.',
      day: ['Producție în atelier', 'Foto produs cu lumină naturală', 'Răspuns la comenzi DM', 'Pregătire colete', 'Planificare colecție nouă'],
      skills: ['Meserie tactilă', 'Foto produs', 'Marketing pe Insta', 'Operațiuni mici', 'Storytelling'],
      paths: ['Brand mic premium', 'Studio + workshop-uri', 'Wholesale la concept stores', 'Maker educator'],
      schools: ['Autodidact + ucenicie', 'UNARTE — Arte Decorative', 'Cursuri scurte (Atelier ID, Make a Point)'],
    },
    {
      id: 'self-taught-engineer', name: 'Self-taught Engineer',
      tagline: 'Fără diplomă, doar cu portofoliu',
      color: 'purple', emoji: '⌬',
      pathType: 'autodidact',
      traits: ['build', 'tech', 'analyze'],
      riasec: ['I', 'R'], big5: ['C', 'O'],
      salary: '3.500 — 10.000 €/lună', demand: 'Foarte mare', vibe: 'Disciplinat + curios',
      description: 'Înveți pe cont propriu (cursuri, proiecte open-source, GitHub), construiești portofoliu, intri în industrie fără facultate de IT.',
      day: ['1h studiu pe un curs online', 'Contribuție la un open-source repo', 'Lucru pe un side-project', 'Networking pe Discord-uri tehnice', 'Aplicare la job-uri remote'],
      skills: ['Self-study', 'Github', 'Build in public', 'Algoritmică', 'Limba engleză'],
      paths: ['Senior Engineer', 'Tech Lead', 'Indie hacker', 'CTO la startup'],
      schools: ['Autodidact (CS50, FreeCodeCamp)', 'Bootcamps RO (Codecool)', 'Optional: PUB după 2 ani de muncă'],
    },
    {
      id: 'medic', name: 'Medic',
      tagline: 'Drum lung, impact direct',
      color: 'green', emoji: '✚',
      pathType: 'facultate',
      traits: ['analyze', 'social', 'tech'],
      riasec: ['I', 'S', 'R'], big5: ['C', 'A'],
      salary: '4.000 — 15.000 €/lună (post-rezidențiat)', demand: 'Foarte mare', vibe: 'Riguros + uman',
      description: 'Studii grele (6+5 ani), dar carieră stabilă cu impact direct asupra vieții oamenilor. Multe specializări — alegi pe parcurs.',
      day: ['Vizite în salon', 'Consultații', 'Discuții cu familii', 'Documentație medicală', 'Studiu continuu pe ghiduri noi'],
      skills: ['Anatomie / fiziologie', 'Empatie clinică', 'Decizii sub presiune', 'Comunicare', 'Învățare continuă'],
      paths: ['Specialist', 'Cercetător clinic', 'Consultant', 'Antreprenor medical'],
      schools: ['UMF Carol Davila', 'UMF Cluj', 'UMF Iași', 'UMF Timișoara'],
    },
    {
      id: 'avocat', name: 'Avocat',
      tagline: 'Argumente, contracte, dreptate',
      color: 'yellow', emoji: '§',
      pathType: 'facultate',
      traits: ['analyze', 'social', 'lead'],
      riasec: ['E', 'I', 'S'], big5: ['C', 'E'],
      salary: '2.500 — 12.000 €/lună', demand: 'Stabilă', vibe: 'Verbal + strategic',
      description: 'Reprezinți clienți în litigii sau consultanță, scrii contracte, navighezi sisteme legale. Multă citire, multă scriere.',
      day: ['Pregătire dosar', 'Audieri în instanță', 'Discuții cu clienții', 'Cercetare legislație', 'Negociere'],
      skills: ['Citit rapid', 'Scriere juridică', 'Argumentare', 'Negociere', 'Etică'],
      paths: ['Partner la cabinet', 'In-house counsel', 'Magistrat', 'Profesor de drept'],
      schools: ['Drept UB', 'Drept UBB', 'Drept SNSPA', 'Drept ASE'],
    },
    {
      id: 'inginer', name: 'Inginer (mecanic / electric)',
      tagline: 'Lucruri reale care trebuie să meargă',
      color: 'purple', emoji: '⚙',
      pathType: 'facultate',
      traits: ['build', 'analyze', 'tech'],
      riasec: ['R', 'I', 'C'], big5: ['C', 'O'],
      salary: '1.500 — 6.000 €/lună', demand: 'Mare', vibe: 'Practic + precis',
      description: 'Proiectezi sisteme fizice — mașini, motoare, instalații, energie. Foarte cerut în industria auto, energie, manufacturing.',
      day: ['Calcule în CAD', 'Vizită pe șantier / fabrică', 'Discuții cu echipa de producție', 'Verificare specificații', 'Testare prototip'],
      skills: ['CAD (SolidWorks)', 'Fizică aplicată', 'Standarde industrie', 'Lucru în echipă', 'Engleză tehnică'],
      paths: ['Project Engineer', 'R&D', 'Operations Manager', 'Antreprenor industrial'],
      schools: ['Politehnica București', 'UPT Timișoara', 'TUIASI Iași', 'UTCN Cluj'],
    },
    {
      id: 'asistent-medical', name: 'Asistent medical generalist',
      tagline: 'Pe linia întâi, cu pacientul, în fiecare zi',
      color: 'green', emoji: '✚',
      pathType: 'profesional',
      traits: ['social', 'analyze', 'build'],
      riasec: ['S', 'I', 'R'], big5: ['A', 'C'],
      salary: '1.000 — 3.500 €/lună (RO) · 2.500 — 5.500 €/lună (UE)', demand: 'Extremă (RO + EU)', vibe: 'Practic + empatic',
      description: 'Postliceala sanitară de 3 ani te face asistent autorizat. Lucrezi în spital, clinică, ambulatoriu, ATI, sau pleci legal în UE după 6 luni de experiență. Cerere imensă, nu competiție.',
      day: ['Recoltări și administrare tratament', 'Monitorizare pacienți', 'Comunicare cu medicul și familia', 'Documentație medicală', 'Proceduri specifice secției'],
      skills: ['Proceduri clinice', 'Empatie sub presiune', 'Engleză/germană (pentru UE)', 'Lucru în echipă', 'Rezistență la stres'],
      paths: ['Specializare ATI / pediatrie / chirurgie', 'Asistent șef', 'Plecare în Germania / Olanda / UK', 'Postliceala → Facultate de medicină (la 30+)'],
      schools: ['Postliceala Sanitară Carol Davila București', 'Postliceala Sanitară Cluj', 'Postliceala Grigore Ghica Vodă Iași'],
    },
    {
      id: 'electrician-autorizat', name: 'Electrician autorizat',
      tagline: 'Trei ani de școală, contract pe loc, propriul atelier la 25',
      color: 'yellow', emoji: '⚡',
      pathType: 'profesional',
      traits: ['build', 'tech', 'analyze'],
      riasec: ['R', 'C', 'I'], big5: ['C'],
      salary: '800 — 2.800 €/lună angajat · 3.000 — 8.000 €/lună propriu atelier', demand: 'Foarte mare', vibe: 'Mâini + cap',
      description: 'Sistemul dual (3 ani) îți dă bursă, masă, și contract de practică plătită din anul 1. Ieși cu autorizație ANRE, poți lucra la firmă sau pe cont propriu. Meserie deficitară — clienții te caută, nu invers.',
      day: ['Citire schemă electrică', 'Tras instalație nouă', 'Diagnoză defecte', 'Punere în funcțiune tablou', 'Discuție cu beneficiarul'],
      skills: ['Citire schemă', 'Norme PE / ISCIR', 'Unelte specifice', 'Calcul putere/secțiune', 'Comunicare cu clientul'],
      paths: ['Maistru electrician', 'Antreprenor — propriul atelier', 'Specializare automatizări industriale', 'Licență la facultatea de Electrotehnică'],
      schools: ['CT Energetic „Remus Răduleț" București', 'CT Electrotimiș', 'Liceul Tehnologic 1 Mai Ploiești', 'CT Reșița'],
    },
    {
      id: 'tehnician-hvac', name: 'Tehnician HVAC / Instalator',
      tagline: 'Aer condiționat, încălzire, sanitare — meseria viitorului ecologic',
      color: 'purple', emoji: '❄',
      pathType: 'profesional',
      traits: ['build', 'tech', 'analyze'],
      riasec: ['R', 'C'], big5: ['C'],
      salary: '900 — 3.200 €/lună angajat · 3.500 — 7.000 €/lună independent', demand: 'În creștere accelerată', vibe: 'Practic + eco',
      description: 'Cu tranziția energetică (pompe de căldură, fotovoltaice, izolare) tehnicienii HVAC sunt ce sunt programatorii pentru IT. Învățământ dual sau liceu tehnologic + autorizație, ieși cu meserie căutată și în RO și în UE.',
      day: ['Montaj sistem climatizare', 'Service centrală termică', 'Punere în funcțiune pompă de căldură', 'Citire planuri instalații', 'Întâlnire cu clientul / arhitectul'],
      skills: ['Termodinamică aplicată', 'Sudură / lipire țevi', 'Diagnoză defecte', 'Norme RoHS / F-Gas', 'Antreprenoriat de bază'],
      paths: ['Specializare pompe de căldură / fotovoltaice', 'Antreprenor — firmă de instalații', 'Energy auditor', 'Tehnician superior — facultate inginerie'],
      schools: ['CT Energetic „Remus Răduleț" București', 'CT Mecanic Grivița', 'CT Electrotimiș', 'CT Iași'],
    },
  ],

  // ── PATHS — facultate vs autodidact vs antreprenor vs profesional ──
  paths: [
    {
      id: 'facultate', name: 'Facultate clasică', emoji: '◆', color: 'purple',
      tagline: 'Diploma, comunitatea, structura',
      duration: '3-6 ani',
      cost: '0 (loc bugetat) — 1.000-2.000 €/an cu taxă (stat sau privat)',
      pros: ['Diplomă recunoscută internațional', 'Comunitate de colegi & profi', 'Structură care te ține pe drum', 'Acces la cercetare, laboratoare'],
      cons: ['Lent — 3+ ani până la primul job real', 'Curricula uneori desincronizată cu industria', 'Cost de oportunitate'],
      bestFor: ['Medicină, drept, inginerie', 'Cercetare, academic', 'Cariere care cer licență'],
      next: ['Caută Top 3 facultăți pe domeniu', 'Vizitează zilele porților deschise', 'Găsește mentori dintre studenții ultimului an'],
    },
    {
      id: 'autodidact', name: 'Autodidact / Bootcamp', emoji: '◉', color: 'green',
      tagline: 'Înveți singur, livrezi proiecte, intri în industrie',
      duration: '6 luni - 2 ani',
      cost: '0 — 5.000€ (bootcamp)',
      pros: ['Rapid — primul job în <1 an posibil', 'Flexibil — la ritmul tău', 'Direct relevant pentru piață', 'Costuri mici sau zero'],
      cons: ['Necesită auto-disciplină reală', 'Fără rețea de colegi automat', 'Recunoaștere variabilă în RO'],
      bestFor: ['Programare, design, marketing digital', 'Schimbare de carieră', 'Cariere skill-based'],
      next: ['Alege un domeniu și un curs flagship (CS50, Odin Project)', 'Construiește 3 proiecte publice', 'Aplici la job-uri junior la 6-9 luni'],
    },
    {
      id: 'antreprenor', name: 'Antreprenor / Founder', emoji: '⚡', color: 'purple',
      tagline: 'Construiești o companie de la zero',
      duration: 'Indefinit',
      cost: '0 — milioane',
      pros: ['Libertate totală', 'Upside nelimitat', 'Înveți rapid', 'Faci ce vrei tu'],
      cons: ['Stres ridicat', 'Venit incert ani la rând', 'Risc real de eșec', 'Nu există off-time'],
      bestFor: ['Oameni cu toleranță la risc', 'Idei validate', 'Cei care vor control total'],
      next: ['Validează 10 conversații cu utilizatori', 'Construiește MVP în 30 zile', 'Aplicii la accelerator (Innovation Labs, Techstars)'],
    },
    {
      id: 'freelance', name: 'Freelance / Solo', emoji: '✦', color: 'yellow',
      tagline: 'Servicii pe proiect, fără șef',
      duration: 'Imediat',
      cost: 'Doar laptop + skill',
      pros: ['Control pe ce proiecte iei', 'Variat — clienți și domenii diferite', 'Fără limita salarială', 'Lucrezi de oriunde'],
      cons: ['Tu ești și CEO + contabil + marketing', 'Venit volatil', 'Singurătate profesională', 'Fără benefits'],
      bestFor: ['Designeri, dezvoltatori, scriitori', 'Cei cu portofoliu solid', 'Cei disciplinați'],
      next: ['Construiește portofoliu cu 3 proiecte', 'Setează profil pe Upwork / Toptal / LinkedIn', 'Stabilește un rate și un proces de onboarding client'],
    },
    {
      id: 'creator', name: 'Creator economy', emoji: '★', color: 'green',
      tagline: 'Audiența e cariera ta',
      duration: '2-5 ani până devine sustenabil',
      cost: '~0',
      pros: ['Brand personal asset pe viață', 'Multiple surse de venit', 'Faci ce-ți place', 'Audiență internațională posibilă'],
      cons: ['Nu există rețetă garantată', 'Public viața ta', 'Algoritm dependent', 'Mulți încep, puțini reușesc'],
      bestFor: ['Creativi cu voce distinctă', 'Experți într-o nișă', 'Persoane disciplinate cu output regulat'],
      next: ['Alege o nișă + format', 'Postează 100 piese fără să te uiți la metrici', 'Monetizează după primii 5.000 fani reali'],
    },
    {
      id: 'profesional', name: 'Școală profesională / Dual VET', emoji: '⚒', color: 'yellow',
      tagline: 'Meserie reală, salariu rapid, fără facultate',
      duration: '1-3 ani (postliceal) / 3-4 ani (dual)',
      cost: '0 (de stat) — burse + masă incluse în dual',
      pros: ['Cerere uriașă de meseriași în RO și UE', 'Practică plătită din anul 1 în sistemul dual', 'Angajare imediată după absolvire (>90%)', 'Posibilitate de a lansa propriul atelier/firmă în 2-3 ani'],
      cons: ['Stigmă socială încă prezentă în RO', 'Mai puțin prestigiu față de „mama vrea să dau la facultate"', 'Mobilitate verticală mai lentă fără bac+facultate'],
      bestFor: ['Cei cu mâini iscusite, mintea practică', 'Tipuri RIASEC R (realist) dominante', 'Cei care vor să producă bani devreme', 'Cei cu interes pentru tehnică, sănătate, construcții, mecanică'],
      next: ['Identifică un liceu tehnologic cu dual în orașul tău', 'Vorbește cu un absolvent — câștigă cât? muncește unde?', 'Pentru sanitar: postliceala, după Bac sau în paralel cu liceul'],
    },
  ],

  // ── UNIVERSITĂȚI / ȘCOLI / BOOTCAMPURI / ACCELERATOARE ──
  // Phase 1 v1 expansion (2026-04-29): ~95 instituții acoperind toate căile.
  // Sursă: cunoștințe RO higher-ed/VET ca de aprilie 2026. NEEDS revizuire vs.
  // ARACIS oficial înainte de lansarea publică. Schema neschimbată, doar
  // valori noi pentru `tier` ('TRADE', 'POST') și `kind` ('liceu-dual',
  // 'postliceala', 'privat-bootcamp', 'accelerator').
  universities: [
    // ── State universities — București ──
    { id: 'pub', name: 'Universitatea Politehnică din București (UPB)', city: 'București', tier: 'TOP', kind: 'stat', tags: ['IT', 'inginerie', 'data'], domains: ['Calculatoare', 'Automatică', 'Electronică', 'Mecanică', 'Energetică', 'Aerospațială'], notes: 'Cel mai mare centru tehnic din RO. Comunitate puternică, recrutori vin pe campus.' },
    { id: 'ub', name: 'Universitatea din București (UB)', city: 'București', tier: 'TOP', kind: 'stat', tags: ['umaniste', 'științe', 'drept', 'IT'], domains: ['Drept', 'Litere', 'Matematică-Informatică', 'Fizică', 'Filosofie', 'Psihologie', 'Sociologie', 'Geografie', 'Istorie', 'Biologie'], notes: 'Cea mai veche și diversă universitate. Tare la drept, mate, științe sociale.' },
    { id: 'ase', name: 'Academia de Studii Economice (ASE)', city: 'București', tier: 'TOP', kind: 'stat', tags: ['business', 'IT'], domains: ['Finanțe', 'Marketing', 'Antreprenoriat', 'Business International', 'Cibernetică-Informatică Economică', 'Contabilitate'], notes: 'Hub-ul de business din RO. Multe programe în engleză și franceză.' },
    { id: 'snspa', name: 'SNSPA — Studii Politice și Administrative', city: 'București', tier: 'TOP', kind: 'stat', tags: ['comunicare', 'umaniste'], domains: ['Comunicare', 'Științe Politice', 'Sociologie', 'Management', 'Relații Internaționale'], notes: 'Cea mai bună pe comunicare și PR în RO.' },
    { id: 'unarte', name: 'UNARTE — Universitatea Națională de Arte', city: 'București', tier: 'TOP', kind: 'stat', tags: ['artă'], domains: ['Pictură', 'Grafică', 'Design', 'Sculptură', 'Modă', 'Foto-Video', 'Istoria Artei'], notes: 'Atmosferă brutală în sens bun — concept-driven.' },
    { id: 'unatc', name: 'UNATC „I.L. Caragiale" — Teatrală și Cinematografică', city: 'București', tier: 'TOP', kind: 'stat', tags: ['artă'], domains: ['Regie Film', 'Regie Teatru', 'Actorie', 'Imagine', 'Multimedia', 'Scenaristică'], notes: 'Pentru cei care vor film, teatru, scenografie. Foarte selectiv.' },
    { id: 'uauim', name: 'UAUIM — Arhitectură și Urbanism „Ion Mincu"', city: 'București', tier: 'TOP', kind: 'stat', tags: ['artă', 'inginerie'], domains: ['Arhitectură', 'Urbanism', 'Design Interior', 'Conservare Patrimoniu'], notes: 'Singura universitate de top de arhitectură în RO. 6 ani.' },
    { id: 'umfcd', name: 'UMF „Carol Davila"', city: 'București', tier: 'TOP', kind: 'stat', tags: ['medicină'], domains: ['Medicină Generală', 'Medicină Dentară', 'Farmacie', 'Asistență Medicală'], notes: 'Top medicină în RO. Concurs greu.' },
    { id: 'usamv-buc', name: 'USAMV București', city: 'București', tier: 'GOOD', kind: 'stat', tags: ['științe', 'medicină'], domains: ['Agronomie', 'Horticultură', 'Zootehnie', 'Medicină Veterinară', 'Biotehnologii', 'Inginerie Alimentară'], notes: 'Singura USAMV din capitală. Bun pe agro-tech și veterinară.' },
    { id: 'unmb', name: 'UNMB — Universitatea Națională de Muzică', city: 'București', tier: 'TOP', kind: 'stat', tags: ['artă'], domains: ['Compoziție', 'Interpretare', 'Dirijat', 'Muzicologie', 'Pedagogie Muzicală'], notes: 'Conservatorul Bucureștean. Tradiție foarte solidă.' },
    { id: 'unefs', name: 'UNEFS — Educație Fizică și Sport', city: 'București', tier: 'GOOD', kind: 'stat', tags: ['științe'], domains: ['Educație Fizică și Sport', 'Kinetoterapie', 'Sport și Performanță Motrică'], notes: 'Pentru cariere în sport, antrenorat, fizioterapie.' },

    // ── State universities — Cluj-Napoca ──
    { id: 'ubb', name: 'UBB — Universitatea Babeș-Bolyai', city: 'Cluj-Napoca', tier: 'TOP', kind: 'stat', tags: ['umaniste', 'științe', 'IT', 'business'], domains: ['Informatică', 'Matematică', 'Psihologie', 'Litere', 'Sociologie', 'Drept', 'Business (FSEGA)', 'Filosofie'], notes: 'Cea mai bine clasată universitate din RO internațional. Multilinguală (RO/HU/EN/DE).' },
    { id: 'utcn', name: 'UTCN — Tehnică Cluj-Napoca', city: 'Cluj-Napoca', tier: 'TOP', kind: 'stat', tags: ['IT', 'inginerie'], domains: ['Calculatoare', 'Automatică', 'Mecanică', 'Construcții', 'Electronică', 'Arhitectură'], notes: 'Politehnica Cluj. Foarte tare pe IT și automotive. Și centrul Nord Baia Mare.' },
    { id: 'umf-cluj', name: 'UMF „Iuliu Hațieganu" Cluj', city: 'Cluj-Napoca', tier: 'TOP', kind: 'stat', tags: ['medicină'], domains: ['Medicină', 'Farmacie', 'Stomatologie', 'Asistență Medicală'], notes: 'Bilingv (română, engleză, franceză).' },
    { id: 'usamv-cluj', name: 'USAMV Cluj-Napoca', city: 'Cluj-Napoca', tier: 'GOOD', kind: 'stat', tags: ['științe', 'medicină'], domains: ['Agronomie', 'Horticultură', 'Zootehnie', 'Medicină Veterinară', 'Silvicultură'], notes: 'Solidă pe biotehnologii și agro-cercetare.' },
    { id: 'amgd', name: 'Academia de Muzică „Gheorghe Dima"', city: 'Cluj-Napoca', tier: 'TOP', kind: 'stat', tags: ['artă'], domains: ['Compoziție', 'Interpretare', 'Dirijat', 'Pedagogie Muzicală'], notes: 'A doua mare academie de muzică din RO.' },
    { id: 'uad', name: 'UAD — Artă și Design Cluj-Napoca', city: 'Cluj-Napoca', tier: 'GOOD', kind: 'stat', tags: ['artă'], domains: ['Pictură', 'Grafică', 'Design', 'Modă', 'Sculptură', 'Foto-Video'], notes: 'Alternativa clujeană la UNARTE. Mai mult focus pe design contemporan.' },

    // ── State universities — Iași ──
    { id: 'uaic', name: 'UAIC — Universitatea „Alexandru Ioan Cuza"', city: 'Iași', tier: 'TOP', kind: 'stat', tags: ['umaniste', 'științe', 'IT'], domains: ['Informatică', 'Matematică', 'Psihologie', 'Litere', 'Drept', 'Economie', 'Fizică', 'Chimie', 'Geografie'], notes: 'Cea mai veche universitate modernă din RO (1860). Fundație solidă pe științe și umanioare.' },
    { id: 'tuiasi', name: 'TUIASI — Tehnică „Gheorghe Asachi" Iași', city: 'Iași', tier: 'GOOD', kind: 'stat', tags: ['IT', 'inginerie'], domains: ['Calculatoare', 'Automatică', 'Construcții', 'Electronică', 'Mecanică', 'Chimie'], notes: 'Comunitate IT solidă. Hub Amazon, Continental.' },
    { id: 'umf-iasi', name: 'UMF „Grigore T. Popa" Iași', city: 'Iași', tier: 'TOP', kind: 'stat', tags: ['medicină'], domains: ['Medicină', 'Farmacie', 'Stomatologie', 'Asistență Medicală', 'Bioinginerie Medicală'], notes: 'Cea mai veche facultate de medicină din RO.' },
    { id: 'usamv-iasi', name: 'USAMV „Ion Ionescu de la Brad" Iași', city: 'Iași', tier: 'GOOD', kind: 'stat', tags: ['științe', 'medicină'], domains: ['Agronomie', 'Horticultură', 'Zootehnie', 'Medicină Veterinară'], notes: 'Specializări pe agro-business și securitate alimentară.' },
    { id: 'arte-iasi', name: 'Universitatea Națională de Arte „George Enescu"', city: 'Iași', tier: 'GOOD', kind: 'stat', tags: ['artă'], domains: ['Muzică', 'Teatru', 'Arte Vizuale', 'Design'], notes: 'Singura universitate de arte din Moldova.' },

    // ── State universities — Timișoara ──
    { id: 'uvt', name: 'UVT — Universitatea de Vest Timișoara', city: 'Timișoara', tier: 'TOP', kind: 'stat', tags: ['umaniste', 'științe', 'IT', 'business', 'artă'], domains: ['Informatică', 'Matematică', 'Psihologie', 'Drept', 'Economie', 'Litere', 'Arte', 'Educație Fizică'], notes: 'Diversificată — tare pe psihologie, mate, econ. Comunitate internațională.' },
    { id: 'upt', name: 'UPT — Politehnica Timișoara', city: 'Timișoara', tier: 'TOP', kind: 'stat', tags: ['IT', 'inginerie'], domains: ['Calculatoare', 'Automatică', 'Electronică', 'Construcții', 'Mecanică', 'Energetică'], notes: 'Hub IT vest. Foarte legată de industria din zonă (Continental, Bosch, Siemens).' },
    { id: 'umft', name: 'UMF „Victor Babeș" Timișoara', city: 'Timișoara', tier: 'TOP', kind: 'stat', tags: ['medicină'], domains: ['Medicină', 'Farmacie', 'Stomatologie', 'Bioinginerie Medicală'], notes: 'A treia mare facultate de medicină din RO.' },
    { id: 'usamv-tim', name: 'USAMV „Regele Mihai I" Timișoara', city: 'Timișoara', tier: 'GOOD', kind: 'stat', tags: ['științe', 'medicină'], domains: ['Agronomie', 'Horticultură', 'Zootehnie', 'Medicină Veterinară', 'Tehnologie Alimentară'], notes: 'Una dintre cele 4 USAMV principale.' },

    // ── State universities — restul țării ──
    { id: 'ovidius', name: 'Universitatea „Ovidius" Constanța', city: 'Constanța', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe', 'medicină', 'IT'], domains: ['Medicină', 'Drept', 'Litere', 'Informatică', 'Inginerie'], notes: 'Cea mai mare universitate din zona litorală.' },
    { id: 'umc', name: 'Universitatea Maritimă Constanța', city: 'Constanța', tier: 'GOOD', kind: 'stat', tags: ['inginerie'], domains: ['Navigație', 'Inginerie Marină', 'Electromecanică Navală'], notes: 'Singura universitate civilă maritimă din RO. Job placement bun pe vase comerciale.' },
    { id: 'ucv', name: 'Universitatea din Craiova', city: 'Craiova', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe', 'inginerie', 'business'], domains: ['Drept', 'Litere', 'Economie', 'Informatică', 'Inginerie Mecanică', 'Agronomie'], notes: 'Universitate comprehensivă pentru sud-vestul țării.' },
    { id: 'umf-craiova', name: 'UMF Craiova', city: 'Craiova', tier: 'GOOD', kind: 'stat', tags: ['medicină'], domains: ['Medicină', 'Farmacie', 'Stomatologie'], notes: 'Medicină acreditată în zona Olteniei.' },
    { id: 'ulbs', name: 'ULBS — „Lucian Blaga" Sibiu', city: 'Sibiu', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe', 'inginerie', 'medicină'], domains: ['Medicină', 'Drept', 'Inginerie', 'Litere', 'Științe Economice'], notes: 'Profil comprehensiv. Hub pentru centrul țării.' },
    { id: 'utbv', name: 'Universitatea „Transilvania" Brașov', city: 'Brașov', tier: 'GOOD', kind: 'stat', tags: ['inginerie', 'IT', 'business', 'medicină'], domains: ['Inginerie Auto', 'Informatică', 'Silvicultură', 'Economie', 'Medicină', 'Design Industrial'], notes: 'Foarte tare pe automotive (parteneriate cu industria).' },
    { id: 'udjg', name: 'UDJG — „Dunărea de Jos" Galați', city: 'Galați', tier: 'GOOD', kind: 'stat', tags: ['inginerie', 'științe', 'medicină'], domains: ['Inginerie Navală', 'Informatică', 'Tehnologie Alimentară', 'Medicină', 'Litere'], notes: 'Singura inginerie navală academică din RO.' },
    { id: 'uoradea', name: 'Universitatea din Oradea', city: 'Oradea', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe', 'medicină'], domains: ['Medicină', 'Drept', 'Inginerie', 'Litere', 'Economie', 'Educație Fizică'], notes: 'Profil larg pentru zona Crișanei.' },
    { id: 'usv', name: 'USV — „Ștefan cel Mare" Suceava', city: 'Suceava', tier: 'GOOD', kind: 'stat', tags: ['IT', 'inginerie', 'umaniste'], domains: ['Informatică', 'Inginerie Electrică', 'Litere', 'Educație', 'Economie'], notes: 'Centrul universitar din Bucovina. Solidă pe IT și produse alimentare.' },
    { id: 'unstpb-pitesti', name: 'UNSTPB — Centrul Universitar Pitești', city: 'Pitești', tier: 'GOOD', kind: 'stat', tags: ['inginerie', 'IT', 'umaniste'], domains: ['Inginerie Auto', 'Informatică', 'Litere', 'Educație Fizică', 'Drept'], notes: 'Fost Universitatea din Pitești, integrată în Politehnica București (2024). Hub auto Dacia.' },
    { id: 'valahia', name: 'Universitatea „Valahia" Târgoviște', city: 'Târgoviște', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe', 'inginerie'], domains: ['Drept', 'Litere', 'Inginerie Electrică', 'Teologie', 'Educație'], notes: 'Universitate medie pentru sud.' },
    { id: 'umf-tgm', name: 'UMF „George Emil Palade" Târgu Mureș', city: 'Târgu Mureș', tier: 'TOP', kind: 'stat', tags: ['medicină'], domains: ['Medicină', 'Farmacie', 'Stomatologie'], notes: 'Bilingv română-maghiară-engleză. Foarte căutată.' },
    { id: 'umfst', name: 'UMFST — Inginerie & Științe Târgu Mureș', city: 'Târgu Mureș', tier: 'GOOD', kind: 'stat', tags: ['inginerie', 'IT'], domains: ['Inginerie', 'Informatică', 'Economie'], notes: 'Brațul tehnic al UMF Târgu Mureș (fost Petru Maior).' },
    { id: 'arte-tgm', name: 'Universitatea de Arte din Târgu Mureș', city: 'Târgu Mureș', tier: 'GOOD', kind: 'stat', tags: ['artă'], domains: ['Teatru', 'Muzică', 'Arte Plastice'], notes: 'Singura universitate de arte cu predare în RO și HU.' },
    { id: 'uvasileal', name: 'Universitatea „Vasile Alecsandri" Bacău', city: 'Bacău', tier: 'GOOD', kind: 'stat', tags: ['inginerie', 'științe', 'umaniste'], domains: ['Inginerie', 'Educație Fizică', 'Litere', 'Educație'], notes: 'Universitate medie pentru Moldova centrală.' },
    { id: 'upet', name: 'Universitatea din Petroșani', city: 'Petroșani', tier: 'GOOD', kind: 'stat', tags: ['inginerie'], domains: ['Inginerie Minieră', 'Mecanică', 'Electrică', 'Economie'], notes: 'Specializare unică pe minerit și energie.' },
    { id: 'uav', name: 'Universitatea „Aurel Vlaicu" Arad', city: 'Arad', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe', 'inginerie'], domains: ['Inginerie Alimentară', 'Educație', 'Drept', 'Economie', 'Teologie'], notes: 'Universitate medie pentru zona vestică.' },
    { id: 'uab', name: 'Universitatea „1 Decembrie 1918" Alba Iulia', city: 'Alba Iulia', tier: 'GOOD', kind: 'stat', tags: ['umaniste', 'științe'], domains: ['Drept', 'Istorie', 'Teologie', 'Economie', 'Geografie'], notes: 'Universitate medie pentru centrul Transilvaniei.' },
    { id: 'upg', name: 'Universitatea Petrol-Gaze Ploiești', city: 'Ploiești', tier: 'GOOD', kind: 'stat', tags: ['inginerie', 'științe'], domains: ['Inginerie Petrol și Gaze', 'Inginerie de Petrochimie', 'Informatică', 'Economie'], notes: 'Singura universitate dedicată industriei petroliere din RO.' },

    // ── Private universities (acreditate ARACIS) ──
    { id: 'spiru-haret', name: 'Universitatea „Spiru Haret"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business', 'IT'], domains: ['Drept', 'Economie', 'Psihologie', 'Educație Fizică', 'Jurnalism', 'Informatică'], notes: 'Cea mai mare universitate privată din RO. Multe specializări la distanță.' },
    { id: 'titu-maiorescu', name: 'Universitatea „Titu Maiorescu"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['medicină', 'business', 'umaniste', 'IT'], domains: ['Medicină Dentară', 'Farmacie', 'Drept', 'Asistență Medicală', 'Psihologie', 'Informatică'], notes: 'Privată cu medicină dentară competitivă (taxe ~€7-9k/an).' },
    { id: 'cantemir', name: 'Universitatea Creștină „Dimitrie Cantemir"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['business', 'umaniste'], domains: ['Drept', 'Relații Internaționale', 'Finanțe', 'Turism', 'Litere'], notes: 'Profil business + umanist. Filiale în Cluj și Timișoara.' },
    { id: 'rau', name: 'Universitatea Româno-Americană (RAU)', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['business', 'IT'], domains: ['Business International', 'Marketing', 'Informatică Economică', 'Drept European'], notes: 'Programe în engleză, parteneriate cu universități din SUA.' },
    { id: 'hyperion', name: 'Universitatea „Hyperion"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business', 'artă'], domains: ['Arte', 'Drept', 'Economie', 'Jurnalism', 'Psihologie'], notes: 'Privată generalistă, mai accesibilă ca preț.' },
    { id: 'titulescu', name: 'Universitatea „Nicolae Titulescu"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business'], domains: ['Drept', 'Relații Internaționale', 'Economie', 'Informatică'], notes: 'Specializată pe drept și relații internaționale.' },
    { id: 'ueb', name: 'Universitatea Ecologică din București', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['științe', 'umaniste'], domains: ['Ecologie', 'Drept', 'Psihologie', 'Inginerie Managerială'], notes: 'Privată cu profil de mediu.' },
    { id: 'artifex', name: 'Universitatea „Artifex"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['business'], domains: ['Finanțe', 'Marketing', 'Management'], notes: 'Privată specializată pe științe economice.' },
    { id: 'bioterra', name: 'Universitatea „Bioterra"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['științe'], domains: ['Tehnologii Alimentare', 'Biotehnologii', 'Drept'], notes: 'Privată cu focus agro-alimentar.' },
    { id: 'athenaeum', name: 'Universitatea „Athenaeum"', city: 'București', tier: 'GOOD', kind: 'privat', tags: ['business', 'umaniste'], domains: ['Finanțe', 'Administrație', 'Comunicare'], notes: 'Privată cu profil business + administrație publică.' },
    { id: 'sapientia', name: 'Universitatea „Sapientia" EMTE', city: 'Cluj-Napoca / Târgu Mureș / Miercurea Ciuc', tier: 'GOOD', kind: 'privat', tags: ['IT', 'inginerie', 'umaniste'], domains: ['Informatică', 'Inginerie', 'Comunicare', 'Studii Umaniste'], notes: 'Universitate maghiară cu predare în limba maghiară. Trei campusuri.' },
    { id: 'bogdan-voda', name: 'Universitatea „Bogdan Vodă"', city: 'Cluj-Napoca', tier: 'GOOD', kind: 'privat', tags: ['business', 'umaniste'], domains: ['Drept', 'Economie', 'Educație Fizică'], notes: 'Privată generalistă în Cluj.' },
    { id: 'avram-iancu', name: 'Universitatea „Avram Iancu"', city: 'Cluj-Napoca', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business'], domains: ['Drept', 'Educație', 'Administrație Publică'], notes: 'Privată pentru studii sociale și juridice.' },
    { id: 'petre-andrei', name: 'Universitatea „Petre Andrei"', city: 'Iași', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business'], domains: ['Drept', 'Asistență Socială', 'Psihologie', 'Economie'], notes: 'Privată cu profil social-juridic în Iași.' },
    { id: 'apollonia', name: 'Universitatea „Apollonia"', city: 'Iași', tier: 'GOOD', kind: 'privat', tags: ['medicină'], domains: ['Medicină Dentară', 'Asistență Medicală', 'Tehnică Dentară'], notes: 'Privată cu focus medicină dentară.' },
    { id: 'mihail-kogalniceanu', name: 'Universitatea „Mihail Kogălniceanu"', city: 'Iași', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business'], domains: ['Drept', 'Economie', 'Comunicare'], notes: 'Privată generalistă în Iași.' },
    { id: 'goldis', name: 'Universitatea de Vest „Vasile Goldiș"', city: 'Arad', tier: 'GOOD', kind: 'privat', tags: ['medicină', 'business', 'umaniste'], domains: ['Medicină', 'Farmacie', 'Drept', 'Economie', 'Educație Fizică'], notes: 'Privată cu medicină acreditată. Și învățământ dual.' },
    { id: 'tibiscus', name: 'Universitatea „Tibiscus"', city: 'Timișoara', tier: 'GOOD', kind: 'privat', tags: ['business', 'umaniste', 'artă'], domains: ['Drept', 'Economie', 'Litere', 'Design Grafic'], notes: 'Privată generalistă în Timișoara.' },
    { id: 'ioan-slavici', name: 'Universitatea „Ioan Slavici"', city: 'Timișoara', tier: 'GOOD', kind: 'privat', tags: ['inginerie', 'business'], domains: ['Inginerie Industrială', 'Informatică', 'Economie'], notes: 'Privată tehnică în vest.' },
    { id: 'agora', name: 'Universitatea „Agora"', city: 'Oradea', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'IT'], domains: ['Drept', 'Informatică', 'Comunicare'], notes: 'Privată mică, profil mixt.' },
    { id: 'emanuel', name: 'Universitatea „Emanuel" Oradea', city: 'Oradea', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business'], domains: ['Teologie', 'Business', 'Asistență Socială'], notes: 'Privată creștină. Programe în engleză.' },
    { id: 'adventus', name: 'Universitatea Adventus', city: 'Cernica', tier: 'GOOD', kind: 'privat', tags: ['umaniste'], domains: ['Teologie', 'Asistență Socială', 'Psihologie'], notes: 'Privată confesională.' },
    { id: 'george-bacovia', name: 'Universitatea „George Bacovia"', city: 'Bacău', tier: 'GOOD', kind: 'privat', tags: ['business', 'umaniste'], domains: ['Drept', 'Economie', 'Marketing'], notes: 'Privată mică în Moldova centrală.' },
    { id: 'brancoveanu', name: 'Universitatea „Constantin Brâncoveanu"', city: 'Pitești', tier: 'GOOD', kind: 'privat', tags: ['business', 'umaniste'], domains: ['Finanțe', 'Marketing', 'Drept', 'Comunicare'], notes: 'Privată cu campusuri în Pitești și Brăila.' },
    { id: 'andrei-saguna', name: 'Universitatea „Andrei Șaguna"', city: 'Constanța', tier: 'GOOD', kind: 'privat', tags: ['umaniste', 'business'], domains: ['Drept', 'Comunicare', 'Educație Fizică'], notes: 'Privată generalistă pentru zona litorală.' },

    // ── Trade schools / Dual VET (învățământ dual + postliceal sanitar) ──
    // Notă: din 2026-2027, școlile profesionale clasice se transformă în
    // licee tehnologice cu calificare nivel 3 (3 ani) sau 4 (4+1 ani).
    { id: 'ct-energetic-buc', name: 'Colegiul Tehnic Energetic „Remus Răduleț"', city: 'București', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Electrician', 'Operator energetic', 'Tehnician electrotehnist', 'Mecanic auto'], notes: 'Învățământ dual cu Enel, ABB, Schneider. Bursă lunară + masă.' },
    { id: 'ct-mecanic-grivita', name: 'Liceul Tehnologic „Dimitrie Gusti"', city: 'București', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Mecanic auto', 'Tinichigiu vopsitor auto', 'Sudor'], notes: 'Dual auto cu Renault, Mercedes, Porsche București.' },
    { id: 'liceul-edison-buc', name: 'Liceul Tehnologic „Edmond Nicolau"', city: 'București', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'IT'], domains: ['Tehnician operator tehnică de calcul', 'Tehnician telecomunicații'], notes: 'IT/electronică cu parteneri industriali.' },
    { id: 'ct-aeronautic-buc', name: 'Liceul Tehnologic „Henri Coandă"', city: 'București', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Mecanic aeronave', 'Tehnician aeronautic'], notes: 'Dual cu TAROM și Aerostar Bacău. Una dintre cele mai cerute școli tehnice.' },
    { id: 'ctauto-cluj', name: 'Colegiul Tehnic „Ana Aslan" / Auto Cluj', city: 'Cluj-Napoca', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Mecanic auto', 'Electrician auto', 'Tinichigiu auto'], notes: 'Dual cu Bosch, Emerson, distribuitori auto Cluj.' },
    { id: 'ct-tehnoton-iasi', name: 'Colegiul Tehnic „Gheorghe Asachi"', city: 'Iași', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'IT', 'inginerie'], domains: ['Tehnician electronist', 'Tehnician operator calcul', 'Mecanic'], notes: 'Dual cu Continental, Delphi, Tehnoton.' },
    { id: 'ct-electrotim', name: 'Colegiul Tehnic „Electrotimiș"', city: 'Timișoara', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Electrician', 'Tehnician electrotehnist', 'Operator CNC'], notes: 'Dual cu Continental, Hella, Bosch Timișoara.' },
    { id: 'ct-emi-galati', name: 'Colegiul Tehnic de Marină „A.I. Cuza"', city: 'Galați', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Mecanic naval', 'Electrician naval', 'Sudor'], notes: 'Dual cu Damen Shipyards Galați.' },
    { id: 'ct-resita', name: 'Colegiul Tehnic Reșița', city: 'Reșița', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Sudor', 'Lăcătuș mecanic', 'Operator CNC', 'Electrician'], notes: '82 locuri dual în 2026 cu UCM Reșița și parteneri locali.' },
    { id: 'lt-1mai-ploiesti', name: 'Liceul Tehnologic „1 Mai" Ploiești', city: 'Ploiești', tier: 'TRADE', kind: 'liceu-dual', tags: ['profesional', 'inginerie'], domains: ['Operator industria petrolieră', 'Mecanic utilaje', 'Electrician'], notes: 'Dual cu OMV Petrom și industria petrochimică.' },
    { id: 'spp-medical-buc', name: 'Școala Postliceală Sanitară „Carol Davila"', city: 'București', tier: 'POST', kind: 'postliceala', tags: ['medicină', 'profesional'], domains: ['Asistent medical generalist', 'Asistent farmacie', 'Asistent radiologie'], notes: '3 ani postliceal. Cerere foarte mare — locuri de muncă în UE.' },
    { id: 'spp-medical-cluj', name: 'Școala Postliceală Sanitară Cluj', city: 'Cluj-Napoca', tier: 'POST', kind: 'postliceala', tags: ['medicină', 'profesional'], domains: ['Asistent medical generalist', 'Asistent farmacie', 'Asistent BFKT'], notes: '3 ani postliceal sanitar. Plasare imediată.' },
    { id: 'spp-medical-iasi', name: 'Postliceala Sanitară „Grigore Ghica Vodă"', city: 'Iași', tier: 'POST', kind: 'postliceala', tags: ['medicină', 'profesional'], domains: ['Asistent medical generalist', 'Asistent farmacie'], notes: '3 ani. Concurs greu, dar plasare 100%.' },

    // ── Bootcamps & private programs ──
    { id: 'codecool', name: 'Codecool', city: 'București / Cluj / Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT', 'autodidact'], domains: ['Full-stack JavaScript', 'Java', 'Python', 'Frontend', 'QA Automation'], notes: 'Bootcamp 12 luni, plată după angajare. Job-garantat (parteneri Endava, Cognizant, Adobe).' },
    { id: 'wantsome', name: 'Wantsome', city: 'Iași / Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT', 'autodidact'], domains: ['Frontend (React)', 'Backend (Node/Java)', 'QA', 'DevOps'], notes: 'Bootcamp românesc cu rată ridicată de plasare. ~6 luni full-time.' },
    { id: 'spor-academy', name: 'Sprk Academy', city: 'București / Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT', 'autodidact'], domains: ['Frontend', 'Backend', 'Mobile (iOS/Android)'], notes: 'Bootcamp cu mentori activi în industrie.' },
    { id: 'kwiat-academy', name: 'Kwiat Academy', city: 'Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT', 'autodidact'], domains: ['Java', 'Spring Boot', 'Microservicii', 'AWS'], notes: 'Specializat pe stack enterprise (banci, telecom).' },
    { id: 'cgs-academy', name: 'CGS Academy', city: 'București / Brașov', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT'], domains: ['.NET', 'Java', 'QA', 'Helpdesk'], notes: 'Academia internă CGS — angajare directă după absolvire.' },
    { id: 'iteach-bg', name: 'iTech Academy', city: 'București / Cluj / Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT'], domains: ['Cybersecurity', 'Cloud (AWS/Azure)', 'Data Engineering'], notes: 'Specializat pe roluri non-dev (security, cloud, data).' },
    { id: 'bigflow', name: 'BigFlow Bootcamp', city: 'Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['IT'], domains: ['Data Engineering', 'Python', 'BigQuery'], notes: 'Bootcamp scurt (3 luni) pe data stack modern.' },
    { id: 'iaa-academy', name: 'IAA Academy', city: 'București / Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['business'], domains: ['Digital Marketing', 'Performance Marketing', 'SEO/SEM'], notes: 'Academia Industriei de Marketing din RO. Cursuri certificate de IAB.' },
    { id: 'design-mentor', name: 'DesignMentor', city: 'Online', tier: 'BOOTCAMP', kind: 'privat-bootcamp', tags: ['artă', 'IT'], domains: ['UX/UI Design', 'Product Design', 'Figma'], notes: 'Bootcamp românesc pentru produs design.' },

    // ── Accelerators & founder programs ──
    { id: 'innovation-labs', name: 'Innovation Labs', city: 'București / Cluj / Iași / Timișoara', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Pre-accelerator', 'Mentorat', 'Pitch', 'Demo Day'], notes: '4 luni pre-accelerator pentru studenți. Gratuit, fără equity. ~700 alumni.' },
    { id: 'techcelerator', name: 'Techcelerator', city: 'București', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat', 'IT'], domains: ['Seed accelerator', 'Mentorat', 'Investiție pre-seed'], notes: 'Pentru startup-uri tech early-stage. Investiție în schimbul unui mic equity.' },
    { id: 'spherik', name: 'Spherik Accelerator', city: 'Cluj-Napoca', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Accelerator', 'Mentorat regional', 'Network UBB-UTCN'], notes: 'Acceleratorul oficial al UBB + UTCN. Focus startup-uri din Transilvania.' },
    { id: 'risi-up', name: 'Rise UP! / Innovation Labs Vest', city: 'Timișoara', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Pre-accelerator', 'Mentorat'], notes: 'Filiera vestică a programului Innovation Labs.' },
    { id: 'founder-institute', name: 'Founder Institute Bucharest', city: 'București', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Idea-to-launch', 'Mentorat', 'Investiție post-program'], notes: 'Filiala românească a Founder Institute (global). 14 săptămâni, online + offline.' },
    { id: 'how-to-web', name: 'How to Web — Spotlight & Mission', city: 'București', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Pitch competition', 'Investitor matchmaking', 'Conferință'], notes: 'Cea mai mare conferință tech-founder din Europa de Est. Programe Spotlight (early-stage) și Mission (growth).' },
    { id: 'techstars', name: 'Techstars', city: 'Internațional', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Top accelerator', 'Funding (~$120k)', 'Network global'], notes: 'Top 1% accelerator. Equity-based, internațional. Aplică oricine din RO la programele EMEA.' },
    { id: 'yc', name: 'Y Combinator', city: 'San Francisco / Remote-friendly', tier: 'PROGRAM', kind: 'accelerator', tags: ['antreprenoriat'], domains: ['Top 10 accelerator global', 'Funding ($500k)', 'Network'], notes: 'Cel mai mare accelerator din lume. UiPath, FintechOS au trecut prin YC.' },
    { id: 'eit-digital', name: 'EIT Digital Master School', city: 'București (UPB) + EU', tier: 'PROGRAM', kind: 'program', tags: ['IT', 'antreprenoriat'], domains: ['Master tech + I&E', 'Mobilitate europeană', 'Bursă EU'], notes: 'Master pe 2 ani în 2 țări UE, cu modul de antreprenoriat. UPB e nod activ.' },
  ],
};
